# Generated by Django 6.0.2 on 2026-02-20 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Début de la semaine (lundi)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='timesheet.employee')),
            ],
            options={
                'verbose_name': 'Feuille de temps',
                'verbose_name_plural': 'Feuilles de temps',
                'ordering': ['-week_start'],
                'unique_together': {('employee', 'week_start')},
            },
        ),
    ]
