# Generated by Django 6.0.2 on 2026-02-20 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_weeklytimesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Lundi'), ('TUE', 'Mardi'), ('WED', 'Mercredi'), ('THU', 'Jeudi'), ('FRI', 'Vendredi'), ('SAT', 'Samedi'), ('SUN', 'Dimanche')], max_length=3, verbose_name='Jour')),
                ('arrival_morning', models.TimeField(blank=True, null=True, verbose_name='Heure d’arrivée (matin)')),
                ('lunch_departure', models.TimeField(blank=True, null=True, verbose_name='Départ dîner')),
                ('lunch_return', models.TimeField(blank=True, null=True, verbose_name='Retour dîner')),
                ('arrival_evening', models.TimeField(blank=True, null=True, verbose_name='Heure d’arrivée (soir)')),
                ('departure_evening', models.TimeField(blank=True, null=True, verbose_name='Heure de départ (soir)')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timesheet.weeklytimesheet')),
            ],
            options={
                'verbose_name': 'Entrée journalière',
                'verbose_name_plural': 'Entrées journalières',
                'ordering': ['timesheet_id', 'day'],
                'unique_together': {('timesheet', 'day')},
            },
        ),
    ]
