# Generated by Django 6.0.2 on 2026-02-20 18:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_dailyentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Taux horaire'),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_regular_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5, verbose_name='Heures normales/semaine'),
        ),
    ]
